Repository OHPick/FE, pull requests merged in 2023-06, with the labels that each got.

#21 #18 [Posting] 포스팅 페이지 디자인 구현, 충돌 해결 (복구 완료)
  package.json
  src/assets/svg/addImage.svg
  src/assets/svg/addressArrow.svg
  src/components/MainPost.jsx
  src/components/PostInput.jsx
  src/components/common/Input/Input.jsx
  src/components/common/Input/input.module.scss
  src/components/common/layout/Layout.jsx
  src/components/common/layout/layout.module.scss
  src/components/common/map/Map.jsx
  src/components/common/map/map.module.scss
  src/pages/login/LoginPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
  src/pages/searchLocation/SearchLocationPage.jsx
  src/pages/searchLocation/sarchLocation.module.scss
  src/shared/Router.jsx
  src/styles/css/button.module.css
  src/styles/css/header.module.css
  src/styles/css/layout.module.css
  src/styles/css/main.module.css
  src/styles/css/map.module.css
  src/styles/css/posting.module.css
  src/styles/css/reset.css
  src/styles/css/sarchLocation.module.css
  src/styles/css/slider.module.css
  src/styles/scss/_mixins.scss
  src/styles/scss/_variables.scss
  src/styles/scss/reset.scss
  yarn.lock
Labels: BugFix, Feat, Design

#22 #18 [Feat] 포스팅 기능 구현, API 연동 및 테스트
  src/apis/posts.js
  src/components/common/nav/Nav.jsx
  src/components/common/slider/Slider.jsx
  src/pages/main/MainPage.jsx
  src/pages/posting/PostingPage.jsx
  src/pages/redirectKakao/RedirectKakaoPage.jsx
  src/pages/searchLocation/SearchLocationPage.jsx
  src/pages/searchLocation/sarchLocation.module.scss
Labels: BugFix, Feat, Design

#27 #23 [Feat] 검색 모달창 디자인 및 기능 구현
  src/components/common/header/Header.jsx
  src/components/common/header/SearchBar.jsx
  src/components/common/header/header.module.scss
  src/components/common/layout/Layout.jsx
  src/contexts/PostsContext.js
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
  src/pages/posting/PostingPage.jsx
  src/pages/redirectKakao/RedirectKakaoPage.jsx
  src/shared/Router.jsx
  src/styles/css/header.module.css
  src/styles/css/layout.module.css
  src/styles/css/main.module.css
  src/styles/css/nav.module.css
  src/styles/css/posting.module.css
  src/styles/css/reset.css
  src/styles/css/sarchLocation.module.css
  src/styles/css/slider.module.css
Labels: Feat, Design

#30 #29 [Fix] 검색 기능 버그 해결, 상세 페이지 라우팅
  src/components/MainPost.jsx
  src/components/common/header/SearchBar.jsx
  src/shared/Router.jsx
Labels: BugFix, Feat

#32 #31 [Design] 로그인 페이지 디자인, Input, FormLabel, AirBox 회원가입 재사용 위해 컴포넌트 생성
  src/assets/img/kakaoButton.png
  src/components/FormLabel.jsx
  src/components/MainPost.jsx
  src/components/common/Input/Input.jsx
  src/components/common/airBox/AirBox.jsx
  src/components/common/input/Input.jsx
  src/components/common/input/input.module.scss
  src/pages/login/LoginPage.jsx
  src/pages/login/login.module.scss
  src/styles/css/input.css
  src/styles/css/input.module.css
Labels: Design

#38 #34 #35 #37 로그인 토큰 저장소 변경 : SessionStorage => cookie로 변경 / 로그인 여부를 확인하여 페이징처리하기 : useContext, PrivateRoutes 사용
  package.json
  src/App.js
  src/apis/auth/login.js
  src/apis/instance.js
  src/components/common/header/SearchBar.jsx
  src/components/common/layout/Layout.jsx
  src/contexts/AuthContext.js
  src/contexts/PostsContext.js
  src/contexts/SearchQueryContext.js
  src/pages/login/LoginPage.jsx
  src/pages/login/login.module.scss
  src/pages/main/MainPage.jsx
  src/shared/PrivateRoutes.jsx
  src/shared/Router.jsx
  src/utils/cookies.js
  yarn.lock
Labels: Feat, Refactor

#40 #39 [Fix] 로그인 여부 확인 AuthContext 이미 로그인한 유저 판별 버그 해결
  src/contexts/AuthContext.js
  src/shared/PrivateRoutes.jsx
Labels: BugFix, Refactor

#43 #4 [Feat] 네비게이션바 로그인 추가
  src/components/common/nav/Nav.jsx
  src/components/common/nav/nav.module.scss
  src/shared/Router.jsx
Labels: Design

#47 #46 [Fix] 로그인 상태의 AuthContext에서 새로고침 시 전역 상태값을 잃어 로그인페이지로 이동하는 버그 해결
  src/contexts/AuthContext.js
  src/pages/main/MainPage.jsx
  src/pages/redirectKakao/RedirectKakaoPage.jsx
  src/shared/Router.jsx
Labels: BugFix, Refactor

#54 #53 [Feat] 글 상세 페이지 - 지도 컴포넌트 연동하여 위치에 해당하는 주소 띄우기
  src/components/common/map/map.module.scss
  src/pages/detail/DetailPage.jsx
  src/pages/searchLocation/SearchLocationPage.jsx
  src/pages/searchLocation/sarchLocation.module.scss
Labels: Feat

#55 #6 [Design] 카카오 맵 디자인 변경
  src/components/common/map/Map.jsx
  src/components/common/map/map.module.scss
  src/components/common/map/map.scss
  src/pages/posting/PostingPage.jsx
  src/pages/searchLocation/SearchLocationPage.jsx
  src/pages/searchLocation/sarchLocation.module.scss
Labels: Feat, Design

#62 #33 [Design] INTRO 페이지 디자인
  src/assets/img/introBannerOutCon.png
  src/assets/img/introBg.jpg
  src/assets/img/introBg2.jpg
  src/assets/svg/bigPost.svg
  src/assets/svg/chat.svg
  src/assets/svg/introPeoples.svg
  src/assets/svg/locationList.svg
  src/assets/svg/logoPurple.svg
  src/components/common/layout/Layout.jsx
  src/components/common/layout/layout.module.scss
  src/components/common/slider/slider.module.scss
  src/pages/intro/IntroBannerSlide.jsx
  src/pages/intro/IntroPage.jsx
  src/pages/intro/intro.module.scss
  src/shared/Router.jsx
  src/styles/scss/_mixins.scss
  src/styles/scss/_variables.scss
  src/styles/scss/reset.scss
Labels: Design

#63 #53 [Feat] 글 상세 페이지, 예약 완료 페이지 지도 컴포넌트 연동하여 주소에 해당하는 위치 띄우기
  src/pages/detail/DetailPage.jsx
  src/pages/reservation/ReservationSuccessPage.jsx
Labels: Feat

#68 #67 [Feat] 글 작성 페이지 - 글 작성 폼 유효성 검사(공백 검사)
  src/apis/posts.js
  src/pages/posting/PostingPage.jsx
Labels: Feat

#70 #10 [Feat] 메인페이지 - 검색 바 전국 UI삭제, 홈 메뉴 클릭 시 초기 검색값으로 리셋 기능 추가
  src/components/common/header/SearchBar.jsx
  src/components/common/nav/Nav.jsx
  src/pages/main/MainPage.jsx
Labels: Feat, Design

#73 #4 [Design] 네비게이션바 로그인 아이콘 제거
  src/components/common/nav/Nav.jsx
Labels: Design

#75 #74 [Design] 인트로 배경 확정, 메인 페이지 디자인 일괄 수정
  src/assets/img/introBg.jpg
  src/assets/img/introBg2.jpg
  src/assets/svg/login.svg
  src/components/MainPost.jsx
  src/components/common/header/Header.jsx
  src/components/common/header/header.module.scss
  src/components/common/layout/layout.module.scss
  src/components/common/nav/nav.module.scss
  src/components/common/slider/Slider.jsx
  src/components/common/slider/slider.module.scss
  src/pages/detail/DetailPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
  src/styles/scss/_variables.scss
Labels: Design

#77 #76 [Design] 글 작성 페이지 - 디자인 일괄 수정
  src/components/PostInput.jsx
  src/hooks/useForm.js
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
  src/pages/searchLocation/sarchLocation.module.scss
  src/styles/scss/_mixins.scss
Labels: Design

#79 #78 [Refactor] 전체 검색 기능 추가, 모든 페이지에서 검색 시 메인 페이지로 이동 후 검색결과 띄우도록 수정
  src/components/common/header/SearchBar.jsx
  src/components/common/header/header.module.scss
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
  src/styles/scss/_mixins.scss
Labels: Feat, Refactor, Design

#81 #80 [Feat] 검색 토글 - 페이지 이동 시 자동으로 토글 닫히는 기능 추가, Logo 클릭 시 검색 결과 초기화
  src/components/common/header/Header.jsx
  src/components/common/header/SearchBar.jsx
  src/components/common/layout/Layout.jsx
  src/contexts/SearchToggleContext.js
Labels: BugFix, Feat, Refactor

#83 #82 [Feat] 좋아요 클릭 시 로그인 여부 확인하여 안내 문구 띄우기
  src/components/common/slider/Slider.jsx
  src/components/common/slider/slider.module.scss
  src/contexts/AuthContext.js
  src/pages/detail/DetailPage.jsx
Labels: Feat

#85 #84 [Feat] 메인 페이지 - 검색 시 타이틀 검색결과로 변경하는 기능
  src/contexts/SearchQueryContext.js
  src/pages/intro/IntroPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
Labels: Feat

#86 #36 [Fix] 마이페이지 - 확대 시 화면 깨짐 수정
  src/components/PostList.jsx
  src/pages/mypage/LikedPosts.jsx
  src/pages/mypage/MyPostsPage.jsx
  src/pages/mypage/MyReservations.jsx
  src/pages/mypage/mypage.module.scss
Labels: BugFix

#88 #87 [Design] 채팅 페이지 - 데이터 없을 때 화면 디자인
  src/components/PostList.jsx
  src/components/common/nav/Nav.jsx
  src/pages/chatting/ChattingPage.jsx
  src/pages/chatting/chatting.module.scss
  src/shared/Router.jsx
Labels: Design

#90 #89 [Design] 회원탈퇴 페이지 디자인
  src/pages/exit/ExitPage.jsx
  src/pages/exit/exit.module.scss
  src/shared/Router.jsx
Labels: Design

#91 #89 [Feat] 회원 탈퇴 기능 구현
  src/apis/mypage.js
  src/pages/exit/ExitPage.jsx
  src/pages/mypage/Mypage.jsx
Labels: Feat

#92 #11 [Fix] 회원가입 에러 시 메인으로 이동하지 않도록 수정, 가입 후 로그인 페이지로 이동
  src/pages/signup/SIgnupPage.jsx
Labels: BugFix

#94 #93 [Fix] 이미지업로드 시 두 번씩 선택해야 하는 문제 수정
  src/pages/posting/PostingPage.jsx
Labels: BugFix

#95 #11 [Design] 제목 라인 수정
  src/pages/signup/signup.module.scss
Labels: Design

#98 #11 [Feat] 회원가입 - 에러 메세지 상세 출력
  src/apis/auth/signup.js
  src/pages/signup/SignupPage.jsx
Labels: Feat

#100 #25 [Design] 상세페이지 - 수정, 삭제 버튼 추가
  src/pages/detail/DetailPage.jsx
  src/pages/detail/detail.module.scss
Labels: Design

#102 #101 글 상세 페이지 - 삭제 기능 구현
  src/apis/posts.js
  src/pages/detail/DetailPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
Labels: Feat

#104 #103 [Feat] Header 컴포넌트 로그인, 로그아웃 기능 추가
  src/assets/svg/headerLogout.svg
  src/assets/svg/login.svg
  src/components/common/header/Header.jsx
Labels: Feat, Design

#106 # 105 [Refactor] 폴더/파일 구조 개선, 리팩토링
  src/apis/auth/kakao.js
  src/apis/auth/login.js
  src/apis/auth/signup.js
  src/apis/detail.js
  src/apis/instance/instance.js
  src/apis/mypage.js
  src/apis/posts.js
  src/apis/reservation.js
  src/components/common/slider/Slider.jsx
  src/hooks/useForm.js
  src/pages/login/LoginPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
  src/pages/mypage/Mypage.jsx
  src/utils/keys.js
Labels: Refactor

#108 #107 [Feat] 채팅페이지 - 소켓 연결
  package.json
  src/apis/chatting.js
  src/components/common/nav/Nav.jsx
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/detail/DetailPage.jsx
  src/pages/mypage/LikedPosts.jsx
  src/pages/mypage/MyReservations.jsx
  src/pages/mypage/Mypage.jsx
  src/shared/Router.jsx
  yarn.lock
Labels: Feat, Design

#110 #36 [Fix] 마이페이지 - import 에러 해결
  src/pages/mypage/Mypage.jsx
Labels: BugFix

#111 #107 [Feat] 채팅방, 채팅 기능 구현 Co-authored-by: v-va <poruch0915@gmail.com>
  src/apis/chatting.js
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
Labels: Feat

#112 #4 [Feat] 네비게이션바 - 채팅, 마이페이지 하위 메뉴 디자인 추가
  src/components/common/nav/Nav.jsx
Labels: Design

#113 #31 [Fix] 로그인 에러코드 변경 반영
  src/apis/auth/login.js
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/login/LoginPage.jsx
Labels: BugFix

#114 #107 [Feat] 채팅페이지 - 디자인 및 스크롤 포커스 기능 구현
  src/components/common/layout/Layout.jsx
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
Labels: Feat

#118 #115 [Refactor] 글 작성 폼 디자인 변경 반영, 리팩토링
  src/components/SelectOptions.jsx
  src/components/common/slider/slider.module.scss
  src/pages/detail/DetailPage.jsx
  src/pages/main/main.module.scss
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
Labels: Refactor, Design

#119 #115 [Refactor] 운영 시간을 select-option에서 input타입으로 모든 시간을 입력 가능하도록 수정
  src/pages/posting/OperatingTime.jsx
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
Labels: Refactor

#120 #107 [Feat] 채팅 목록 페이지, 방 생성 기능 구현
  src/apis/chatting.js
  src/assets/img/profileDefault.png
  src/assets/svg/chatListRightArrow.svg
  src/components/PostList.jsx
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
  src/pages/detail/DetailPage.jsx
  src/styles/scss/_mixins.scss
Labels: Feat

#121 #107 [Fix] 채팅페이지 - 데이터 로드 시 문제 해결
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomPage.jsx
Labels: BugFix

#122 #107 [Fix] 채팅목록 - 버그 수정
  src/pages/detail/DetailPage.jsx
Labels: BugFix

#123 #74 [Feat] 인트로 페이지 애니메이션 추가 / 모바일 반응형 디자인 수정
  src/pages/intro/IntroBannerSlide.jsx
  src/pages/intro/intro.module.scss
  src/styles/scss/_mixins.scss
Labels: Feat

#126 #125 [Refactor] 렌더링 최적화 - 윈도우 포커싱 시 refetch 실행 옵션 변경
  src/index.js
Labels: Refactor

#127 #107 [Feat] 채팅페이지 - 유저 상태에 따른 페이지 이동
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/detail/DetailPage.jsx
Labels: Feat

#128 #25 [Fix] 상세페이지 - 로딩 에러 해결
  src/pages/detail/DetailPage.jsx
Labels: BugFix

#131 #40 인트로 페이지 디자인 변경 반영 및 반응형 작업
  src/assets/img/introBannerOutCon.png
  src/assets/svg/introPeoples.svg
  src/pages/intro/intro.module.scss
  src/styles/css/chatting.module.css
  src/styles/css/detail.module.css
  src/styles/css/exit.module.css
  src/styles/css/header.module.css
  src/styles/css/input.module.css
  src/styles/css/intro.module.css
  src/styles/css/layout.module.css
  src/styles/css/login.module.css
  src/styles/css/main.module.css
  src/styles/css/map.css
  src/styles/css/mypage.module.css
  src/styles/css/nav.module.css
  src/styles/css/posting.module.css
  src/styles/css/reservation.module.css
  src/styles/css/reset.css
  src/styles/css/sarchLocation.module.css
  src/styles/css/signup.module.css
  src/styles/css/slider.module.css
  src/styles/scss/_mixins.scss
  src/styles/scss/_variables.scss
  src/styles/scss/reset.scss
Labels: Design

#132 #38 [Feat] 글작성 페이지 폼 유효성 검사 가격, 인원, 시간 숫자 검사 추가
  src/pages/intro/IntroBannerSlide.jsx
  src/pages/posting/OperatingTime.jsx
  src/pages/posting/PostingPage.jsx
Labels: Feat

#133 #33 [Design] 인트로 페이지 초기화면 디자인 변경
  src/assets/svg/introStart.svg
  src/pages/intro/IntroPage.jsx
  src/pages/intro/intro.module.scss
  src/styles/css/intro.module.css
  src/styles/css/reset.css
  src/styles/scss/_mixins.scss
  src/styles/scss/reset.scss
Labels: Design

#134 #33 [Design] 인트로 디자인 및 반응형 디자인 변경
  src/pages/intro/intro.module.scss
  src/styles/css/intro.module.css
Labels: Design

#136 #135 [Design] ORG 설정하기
  public/index.html
  src/assets/img/org.png
  src/pages/intro/intro.module.scss
  src/styles/css/intro.module.css
Labels: Feat

#137 #135 [Design] ORG 설정하기 이미지 안나오는 오류, url 수정
  public/index.html
Labels: BugFix, Feat

#139 #107 [Fix] 채팅페이지 - 글 조회 시 채팅 방 자동 생성 문제 해결
  src/pages/detail/DetailPage.jsx
Labels: BugFix

#141 #115 글 작성 페이지 이미지 미리보기 버튼 디자인 수정
  public/index.html
  src/assets/svg/xBox.svg
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
  src/styles/css/posting.module.css
Labels: Design

#142 #135 [Fix] org이미지 나오지 않는 문제 해결
  public/index.html
Labels: BugFix

#144 #143 [Feat] 포스팅페이지 - 상세페이지 연동 및 작성한 데이터 조회
  src/hooks/useForm.js
  src/pages/detail/DetailPage.jsx
  src/pages/posting/PostingPage.jsx
  src/recoil/atom.js
Labels: Feat

#147 #146 [Feat] 상세페이지 - 작성자 프로필 추가
  src/pages/detail/DetailPage.jsx
  src/pages/detail/detail.module.scss
Labels: Feat, Design

#148 #145 [Chore] React-query devtools 연동
  src/index.js
Labels: Chore

#149 #143 [Fix] 글 수정 기능 테스트 및 이미지 미리보기 버튼 병합 누락 다시 반영, 포스팅 페이지 편의시설, 운영시간 …
  src/pages/posting/PostingPage.jsx
Labels: BugFix

#151 #150 [Feat] 예약현황 페이지 - 예약취소, 예약확인 기능 구현
  src/apis/detail.js
  src/apis/reservation.js
  src/components/PostList.jsx
  src/pages/detail/DetailPage.jsx
  src/pages/mypage/MyReservations.jsx
  src/pages/mypage/mypage.module.scss
  src/pages/posting/PostingPage.jsx
  src/pages/reservation/ReservationPage.jsx
  src/pages/reservation/ReservationSuccessPage.jsx
  src/pages/reservation/reservation.module.scss
  src/shared/Router.jsx
Labels: Feat, Design

#152 #146 [Feat] 상세페이지 - 글 작성자에게는 좋아요 등 버튼 숨김 처리
  src/pages/detail/DetailPage.jsx
Labels: Feat

#153 #56 [Feat] 예약페이지 - 예외처리
  src/pages/reservation/ReservationPage.jsx
Labels: Feat

#154 #67 [Design] 인트로 클릭 효과 없애고 딜레이 2.5초로 변경
  src/pages/intro/IntroPage.jsx
  src/pages/intro/intro.module.scss
Labels: Design

#155 #74 [Design] 인트로 디자인 일괄 변경 작업
  src/assets/svg/introSlide1.svg
  src/assets/svg/introSlide2.svg
  src/assets/svg/introSlide3.svg
  src/assets/svg/introSlide4.svg
  src/pages/intro/IntroBannerSlide.jsx
  src/pages/intro/IntroPage.jsx
  src/pages/intro/intro.module.scss
  src/styles/scss/_mixins.scss
Labels: Design

#158 #157 [Feat] 회원가입 - 유효성 검사 기능 수정
  src/apis/auth/signup.js
  src/pages/signup/SignupPage.jsx
  src/pages/signup/signup.module.scss
Labels: Feat, Design

#160 #159 [Feat] 글 작성 페이지 - 멀티 이미지 업로드
  src/apis/posts.js
  src/pages/posting/PostingPage.jsx
Labels: Feat, Design

#161 #157 [Feat] 회원가입 - 이메일, 코드 인증 시 input 비활성화
  src/apis/auth/signup.js
  src/components/common/input/Input.jsx
  src/pages/signup/SignupPage.jsx
  src/pages/signup/signup.module.scss
Labels: Feat

#163 #162 [Refactor] utils폴더에 재사용 코드 정리
  src/apis/chatting.js
  src/apis/instance/instance.js
  src/components/common/header/Header.jsx
  src/contexts/AuthContext.js
  src/pages/edit/EditPage.jsx
  src/pages/exit/ExitPage.jsx
  src/pages/intro/intro.module.scss
  src/pages/login/LoginPage.jsx
  src/pages/mypage/Mypage.jsx
  src/pages/posting/PostingPage.jsx
  src/shared/Router.jsx
  src/utils/constants/keys.js
  src/utils/constants/posting.js
  src/utils/helpers/cookies.js
  src/utils/helpers/helpers.js
Labels: Refactor

#164 #159 [Feat] 멀티 이미지 업로드 기능 구현 및 디자인(프리뷰 추가,삭제 디자인)
  src/apis/posts.js
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
  src/utils/constants/posting.js
Labels: Feat, Refactor, Design

#166 #165 [Feat] 상세페이지 - 변경된 입력 양식에 맞게 데이터 가져오도록 수정
  src/pages/detail/DetailPage.jsx
Labels: Feat

#167 #159 [Fix] 멀티 이미지 업로드 - 이미지 확장자 없이 _blob으로 업로드 되는 문제 해결
  src/apis/posts.js
Labels: BugFix

#168 #159 [Fix] 멀티 이미지 업로드 - 이미지 확장자 없이 _blob으로 업로드 되는 문제 해결 BugFix, intro…
  src/apis/posts.js
  src/components/common/header/header.module.scss
  src/components/common/slider/Slider.jsx
  src/pages/intro/intro.module.scss
  src/pages/posting/PostingPage.jsx
  src/pages/searchLocation/sarchLocation.module.scss
Labels: BugFix, Refactor, Design

#169 #140 [Design] 모바일 반응형 인트로 깨지는 부분 수정
  src/pages/intro/IntroPage.jsx
  src/pages/intro/intro.module.scss
Labels: Design

#170 #150 [Feat] 예약페이지 API 수정 반영 (하나의 포스트에 여러 날 예약 가능)
  src/apis/reservation.js
  src/components/PostList.jsx
  src/pages/mypage/MyReservations.jsx
  src/pages/reservation/ReservationPage.jsx
  src/pages/reservation/ReservationSuccessPage.jsx
  src/shared/Router.jsx
Labels: Feat

#171 #36 [Feat] 마이페이지 - 좋아요, 나의오피스, 예약현황 리스트에 멀티이미지 중 첫 번째 이미지 출력
  src/components/PostList.jsx
Labels: Feat

#172 #56 [Fix] 예약페이지 - 예외처리 수정
  src/apis/reservation.js
  src/pages/reservation/ReservationPage.jsx
Labels: BugFix

#173 #101 [Feat] 상세 페이지 에러 핸들링 추가
  src/apis/posts.js
  src/pages/detail/DetailPage.jsx
Labels: Feat

#174 #36 [Feat] 마이페이지 - 예외처리
  src/apis/mypage.js
  src/pages/exit/ExitPage.jsx
Labels: Feat

#175 #8 [Feat] 메인 페이지 자기 게시물일 경우 좋아요 버튼 없애는 기능 추가
  src/components/common/slider/Slider.jsx
  src/components/common/slider/slider.module.scss
Labels: Feat

#177 #176 [Feat] 포스팅페이지 - 글 수정 페이지에서 데이터 불러오기까지 구현
  src/apis/posts.js
  src/pages/detail/DetailPage.jsx
  src/pages/edit/EditPage.jsx
  src/pages/posting/PostingPage.jsx
  src/shared/Router.jsx
Labels: Feat

#179 #178 [hotFix] 수정 기능 임시 막기
  src/pages/posting/PostingPage.jsx
Labels: BugFix

#180 #178 [hotFix] 유저 테스트 전 긴급 수정
  src/components/common/header/Header.jsx
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
  src/pages/intro/intro.module.scss
  src/pages/mypage/Mypage.jsx
Labels: BugFix

#182 #178 [hotFix] 콘솔 지우기, 로그아웃 api 거치도록 다시 수정
  src/apis/chatting.js
  src/components/common/header/Header.jsx
  src/pages/chatting/ChattingListPage.jsx
  src/pages/mypage/MyReservations.jsx
  src/pages/mypage/Mypage.jsx
Labels: HotFix

#184 #178 [Fix] 카카오 회원가입 후 이메일 가입 시 중복 안내
  src/pages/signup/SignupPage.jsx
Labels: BugFix

#185 #178 [Fix] 회원 탈퇴 시 상태 update
  src/pages/exit/ExitPage.jsx
Labels: BugFix

#186 #178 [Fix] 채팅방 current 메세지에 프로필 이미지 깨짐 수정
  src/pages/chatting/ChattingRoomPage.jsx
Labels: BugFix

#187 #178 [hotFix] 포스팅 페이지 이미지 용량 제한 경고 에러 핸들링
  src/apis/posts.js
  src/pages/posting/PostingPage.jsx
Labels: BugFix

#189 #188 [Feat] 프로필 수정페이지 - 디자인, 기능 구현
  src/apis/mypage.js
  src/pages/detail/DetailPage.jsx
  src/pages/exit/ExitPage.jsx
  src/pages/exit/exit.module.scss
  src/pages/mypage/Mypage.jsx
  src/pages/mypage/Profile.jsx
  src/pages/mypage/mypage.module.scss
  src/pages/searchLocation/SearchLocationPage.jsx
  src/pages/searchLocation/sarchLocation.module.scss
  src/recoil/atom.js
  src/shared/Router.jsx
Labels: Feat, Design

#190 #178 [Fix] 채팅 입력란, 버튼 수정
  src/pages/chatting/chatting.module.scss
Labels: Design

#191 #178 [Fix] 회원 탈퇴 - 예외 처리 추가
  src/pages/exit/ExitPage.jsx
Labels: BugFix

#192 #178 [Fix] 회원 탈퇴 - 예외 처리 추가
  src/pages/exit/ExitPage.jsx
  src/pages/exit/exit.module.scss
Labels: BugFix

#194 #193 [Refactor] 무한 스크롤 기능 구현 - Intersection Observer API
  src/components/common/header/SearchBar.jsx
  src/components/common/slider/Slider.jsx
  src/contexts/SearchQueryContext.js
  src/pages/main/MainPage.jsx
  src/pages/posting/PostingPage.jsx
  src/utils/constants/constants.js
Labels: BugFix, Feat, Refactor

#195 #193 [Fix] 버그 해결 안됨, 무한 스크롤 전 버전으로 되돌리기
  src/components/common/header/SearchBar.jsx
  src/pages/main/MainPage.jsx
Labels: Remove

#197 #196 [Feat] 예약 페이지 - 달력 클릭 일자, 예약 리스트 표시
  src/pages/detail/DetailPage.jsx
  src/pages/reservation/ReservationPage.jsx
  src/pages/reservation/reservation.module.scss
  src/shared/Router.jsx
Labels: Feat, Design

#200 #198 #199 [[Refactor] 무한스크롤 - 성능 개선(캐싱, 속도) / react-query의 useInfiniteQuery 도입
  package.json
  src/pages/main/MainPage.jsx
  yarn.lock
Labels: BugFix, Refactor

#203 #202 [Design] Nav bar - 포스팅 버튼 Nav로 이동, 기존 포스팅 자리에 스크롤 탑 버튼 추가
  src/assets/svg/postIcon.svg
  src/assets/svg/topIcon.svg
  src/components/common/nav/Nav.jsx
  src/components/common/nav/nav.module.scss
Labels: Design

#204 #201 유저피드백 반영 - UI/UX 디자인 관련
  src/apis/auth/kakao.js
  src/components/common/header/Header.jsx
  src/components/common/header/header.module.scss
  src/components/common/layout/layout.module.scss
  src/components/common/nav/Nav.jsx
  src/components/common/slider/Slider.jsx
  src/components/common/slider/slider.module.scss
  src/pages/login/LoginPage.jsx
  src/shared/PrivateRoutes.jsx
  src/styles/scss/reset.scss
Labels: Design

#207 #188 [Feat] 프로필 페이지 - 예외처리
  src/pages/mypage/Profile.jsx
Labels: Feat

#208 [Feat] 상세페이지 - 유저 프로필 이미지 출력
  src/pages/detail/DetailPage.jsx
  src/pages/detail/detail.module.scss
Labels: Feat

#211 #201 [Fix] 유저 피드백 - 채팅 페이지 stomp 콘솔 로그 삭제
  src/apis/chatting.js
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
Labels: BugFix, Refactor

#212 #201 [Design] 유저 피드백 - 채팅 input 사이즈 조절
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
Labels: Design

#213 #210 [Feat] 채팅 페이지 - 안 읽은 메세지 표시 기능
  src/pages/chatting/ChattingListPage.jsx
  src/pages/chatting/ChattingRoomPage.jsx
  src/pages/chatting/chatting.module.scss
Labels: Feat, Design

#214 #209 [Refactor] 전역 상태 관리 - useContext -> recoil로 변경 / 리팩토링
  src/App.js
  src/apis/posts.js
  src/atoms/authAtom.js
  src/atoms/scrollTopAtom.js
  src/atoms/searchQueryAtom.js
  src/atoms/searchToggleAtom.js
  src/components/common/header/Header.jsx
  src/components/common/header/SearchBar.jsx
  src/components/common/layout/Layout.jsx
  src/components/common/nav/Nav.jsx
  src/components/common/nav/nav.module.scss
  src/components/common/slider/Slider.jsx
  src/contexts/AuthContext.js
  src/contexts/SearchQueryContext.js
  src/contexts/SearchToggleContext.js
  src/hooks/useAuth.js
  src/hooks/useSearchQuery.js
  src/hooks/useSearchToggle.js
  src/pages/detail/DetailPage.jsx
  src/pages/exit/ExitPage.jsx
  src/pages/login/LoginPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/mypage/Mypage.jsx
  src/pages/redirectKakao/RedirectKakaoPage.jsx
  src/recoil/atom.js
  src/shared/PrivateRoutes.jsx
Labels: Refactor

#215 #181 [Feat] 무한스크롤 스크롤탑 기능 추가
  src/components/common/nav/Nav.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/main.module.scss
Labels: Feat

#216 #178 [hotFix] 콘솔 제거
  src/pages/main/MainPage.jsx
  src/shared/PrivateRoutes.jsx
Labels: HotFix

#217 #201 [Ractor] 유저 피드백 - 카카오 로그인 시 뒤로가면 다시 로그인 요청 및 성공 alert뜸 -> 로그인 되어…
  src/pages/login/LoginPage.jsx
Labels: Refactor

#218 #201 [Style] 유저 피드백 - console log 삭제
  src/apis/auth/signup.js
  src/apis/posts.js
  src/pages/detail/DetailPage.jsx
  src/pages/mypage/Profile.jsx
  src/pages/reservation/ReservationSuccessPage.jsx
  src/pages/signup/SignupPage.jsx
Labels: Style

#221 #220 [Refactor] 로그인 보안 문제 개선 - Https 쿠키 설정 Refactor
  src/apis/auth/login.js
  src/apis/instance/instance.js
  src/components/common/slider/Slider.jsx
  src/index.js
Labels: Refactor

#222 #220 [Refactor] 쿠키 만료시간 2일로 설정
  src/apis/instance/instance.js
Labels: Refactor

#223 #178 [Fix] 슬라이드 안움직이는 버그 해결
  src/components/common/slider/Slider.jsx
Labels: BugFix

#225 #224 [Improve] 이미지 성능개선 - lazy loading 처리
  src/components/PostList.jsx
  src/components/common/slider/Slider.jsx
  src/pages/chatting/ChattingListPage.jsx
Labels: Refactor

#226 #224 [Improve] 이미지 성능개선 - lazy loading 처리
  src/components/MainPost.jsx
  src/components/PostList.jsx
  src/pages/mypage/LikedPosts.jsx
  src/pages/mypage/Mypage.jsx
Labels: Refactor

#227 #224 [Improve] 웹 접근성 최적화, 검색 엔진 최적화
  public/robots.txt
  src/components/common/nav/Nav.jsx
  src/components/common/slider/Slider.jsx
  src/pages/intro/IntroBannerSlide.jsx
Labels: Refactor

#228 #224 [Improve] 웹 성능 최적화 - 콘텐츠가 포함된 최대 페인트 이미지 미리 로드
  src/components/common/slider/Slider.jsx
Labels: Refactor

#229 #188 [Fix] 프로필 수정 - 이미지 다운로드 시 CORS 에러 수정
  src/pages/mypage/Profile.jsx
Labels: BugFix

#230 #224 [Fix] slider id속성 대신 dataset이용해 페이지 매칭, 뒤로가기 시 경로 중첩이벤트 적용 개선, '…
  src/components/MainPost.jsx
  src/components/common/slider/Slider.jsx
Labels: BugFix

#231 #224 [Improve] 목록에 <li> 요소와 스크립트 지원 요소(<script> 및 <template>)만 포함되지 않음
  src/components/common/slider/Slider.jsx
Labels: Refactor

#232 #224 [Fix] mainPost 경로 설정 누락 다시 추가
  src/components/MainPost.jsx
Labels: HotFix

#233 #224 [Improve] 이미지 파일 크기 안내 추가, input 라벨추가로 웹 접근성 개선
  src/pages/posting/OperatingTime.jsx
  src/pages/posting/PostingPage.jsx
  src/pages/posting/posting.module.scss
Labels: Refactor

#234 #224 [Improve] 이미지 파일 크기 안내 추가, input 라벨추가로 웹 접근성 개선 라벨 누락 수정
  src/pages/posting/PostingPage.jsx
Labels: BugFix

#237 #201 [Refactor] 유저 피드백 개선 - 최대 인원 0명에서 1명으로 변경
  src/pages/posting/PostingPage.jsx
Labels: Refactor

#240 #238 [Fix] 로그인 - 보안 강화 / 고도화 작업
  src/apis/instance/instance.js
Labels: BugFix

#241 #238 [Improve] 로그인 - 보안 강화 / 고도화 작업
  src/apis/instance/instance.js
  src/hooks/useAuth.js
  src/shared/PrivateRoutes.jsx
Labels: BugFix

#244 #238 [Fix] 새로 고침 시 reissue가 여러번 실행되는 문제 해결
  src/components/common/layout/Layout.jsx
  src/components/common/nav/Nav.jsx
  src/components/common/slider/Slider.jsx
  src/hooks/useAuth.js
Labels: BugFix

#245 #143 [Feat] 포스팅페이지 - 글 수정 기능(멀티 이미지 수정 기능)
  src/apis/posts.js
  src/pages/mypage/Profile.jsx
  src/pages/posting/PostingPage.jsx
Labels: Feat
